version: "3"
services:
  bot:
    build: .
    restart: on-failure
    entrypoint: node /app/eris.js
    volumes:
      - "./:/app"
      - "./files:/package"
    environment:
      - "DISCORD_TOKEN=NzU4NzQ0MTM5Nzg4NzEzOTg0.X2zZiw.SIqfMYauoyfkbvB9Jt8Lj72otfU"