#!/bin/bash
SP="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
cd $SP
docker-compose -f $SP/docker-compose.yml up -d
rm ../logs/eris.log&&touch ../logs/eris.log
docker logs -f eris_bot_1 &> ../logs/eris.log &