version: "2.4"
services:
  discordjs:
    build: ./discord.js/
    restart: always
    pid: "host"
    entrypoint: node /app/discord.js.js
    volumes:
      - "./discord.js/:/app"
    environment:
      - "DISCORD_TOKEN=${JS}"
      - "HID=${HID}"
  discordrb:
    build: ./discordrb/
    pid: "host"
    restart: always
    entrypoint: ruby /app/discordrb.rb
    volumes:
      - "./discordrb/:/app"
    environment:
      - "DISCORD_TOKEN=${RB}"
      - "HID=${HID}"
  eris:
    build: ./eris/
    pid: "host"
    restart: always
    entrypoint: node /app/eris.js
    volumes:
      - "./eris/:/app"
    environment:
      - "DISCORD_TOKEN=${ERIS}"
      - "HID=${HID}"
  discordgo:
    build: ./discordgo/
    restart: always
    pid: "host"
    entrypoint: go run /app/discordgo.go
    volumes:
      - "./discordgo/:/app"
    environment:
      - "DISCORD_TOKEN=${GO}"
      - "HID=${HID}"
  discordpy:
    build: ./discord.py/
    restart: always
    pid: "host"
    entrypoint: python3 -u /app/discord.py.py
    volumes:
      - "./discord.py/:/app"
    environment:
      - "JISHAKU_HIDE=True"
      - "JISHAKU_NO_UNDERSCORE=True"
      - "DISCORD_TOKEN=${PY}"
      - "HID=${HID}"
  discordia:
    build: ./discordia/
    restart: always
    pid: "host"
    entrypoint: bash /app/run.bash
    volumes:
      - "./discordia/:/app"
    environment:
      - "DISCORD_TOKEN=${LUA}"
      - "HID=${HID}"
  logging_dummy:
    build: ./dummies/
    restart: always
    pid: "host"
    entrypoint: python3 -u /app/bot.py
    volumes:
      - "./dummies/:/app"
    environment:
      - "DISCORD_TOKEN=${LD}"
      - "DISCORD_PFX=log."
      - "HID=${HID}"
  misc_dummy:
    build: ./dummies/
    restart: always
    pid: "host"
    entrypoint: python3 -u /app/bot.py
    volumes:
      - "./dummies/:/app"
    environment:
      - "DISCORD_TOKEN=${MISC}"
      - "DISCORD_PFX=misc."
      - "HID=${HID}"
  insecure_dummy:
    build: ./dummies/
    restart: always
    pid: "host"
    entrypoint: python3 -u /app/bot.py
    volumes:
      - "./dummies/:/app"
    environment:
      - "DISCORD_TOKEN=${INSD}"
      - "DISCORD_PFX=insec."
      - "HID=${HID}"
  discordjl:
    build: ./discord.jl/
    restart: always
    pid: "host"
    entrypoint: bash /app/run.bash
    volumes:
      - "./discord.jl/:/app"
    environment:
      - "DISCORD_TOKEN=${JL}"
      - "HID=${HID}"
  secure_dummy:
    build: ./dummies/
    restart: always
    pid: "host"
    entrypoint: python3 -u /app/bot.py
    volumes:
      - "./dummies/:/app"
    environment: 
      - "DISCORD_TOKEN=${SECD}"
      - "DISCORD_PFX=sec."
      - "HID=${HID}"
  garbage_dummy:
    build: ./dummies/
    restart: always
    pid: "host"
    entrypoint: python3 -u /app/bot.py
    volumes:
      - "./dummies/:/app"
    environment: 
      - "DISCORD_TOKEN=${TRASHD}"
      - "DISCORD_PFX=trash."
      - "HID=${HID}"
  discordcr:
    build: ./discordcr/
    entrypoint: bash /app/run.bash
    environment:
    - "DISCORD_TOKEN=${CR}"
    - "DISCORD_ID=${CRID}"
    - "HID=${HID}"
    pid: host
    restart: always
    volumes:
      - "./discordcr/:/app"
  potato_dummy:
    build: ./dummies/
    restart: always
    pid: "host"
    entrypoint: python3 -u /app/bot.py
    volumes:
      - "./dummies/:/app"
    environment: 
      - "DISCORD_TOKEN=${POTATE}"
      - "DISCORD_PFX=potato."
      - "HID=${HID}"
  rpc1:
    build: ./rpc1/
    restart: always
    pid: "host"
    entrypoint: python3 -u /app/bot.py
    volumes:
      - "./rpc1/:/app"
    environment: 
      - "DISCORD_TOKEN=${RPC1}"
      - "HID=${HID}"
  rpc2:
    build: ./rpc2/
    restart: always
    pid: "host"
    entrypoint: python3 -u /app/bot.py
    volumes:
      - "./rpc2/:/app"
    environment: 
      - "DISCORD_TOKEN=${RPC2}"
      - "HID=${HID}"
  rpc3:
    build: ./rpc3/
    restart: always
    pid: "host"
    entrypoint: python3 -u /app/bot.py
    volumes:
      - "./rpc3/:/app"
    environment: 
      - "DISCORD_TOKEN=${RPC3}"
      - "HID=${HID}"
  rpc4:
    build: ./rpc4/
    restart: always
    pid: "host"
    entrypoint: python3 -u /app/bot.py
    volumes:
      - "./rpc4/:/app"
    environment: 
      - "DISCORD_TOKEN=${RPC4}"
      - "HID=${HID}"
  detriusjs:
    build: ./detriusjs/
    restart: always
    pid: "host"
    entrypoint: bash /app/run.bash
    volumes:
      - "./detriusjs/:/app"
    environment: 
      - "DISCORD_TOKEN=${TS}"
      - "HID=${HID}"
  dimscord:
    build: ./dimscord/
    restart: always
    pid: "host"
    entrypoint: nim c -r -d:ssl --warnings:off --hints:off /app/dimscordnim.nim
    volumes:
      - "./dimscord/:/app"
    environment: 
      - "DISCORD_TOKEN=${NIM}"
      - "HID=${HID}"
  discordphp:
    build: ./discordphp/
    restart: always
    pid: "host"
    entrypoint: php /app/discordphp.php
    volumes:
      - "./discordphp/:/app"
    environment: 
      - "DISCORD_TOKEN=${PHP}"
      - "HID=${HID}"
  serenity:
    build: 
      context: ./serenity/
      args:
        - "DISCORD_TOKEN=${RS}"
        - "HID=${HID}"
    restart: always
    pid: "host"
    entrypoint: /app/target/debug/bot
    volumes:
      - "./serenity/Cargo.toml:/app/Cargo.toml"
      - "./serenity/serenity.rs.rs:/app/src/main.rs"
      - "./serenity/run.bash:/run.bash"
    environment:
      - "DISCORD_TOKEN=${RS}"
      - "HID=${HID}"
  utilities:
    build: ./utilities/
    restart: always
    pid: "host"
    entrypoint: python3 -u /app/bot.py
    volumes:
      - "./utilities/:/app"
    environment:
      - "JISHAKU_HIDE=True"
      - "JISHAKU_NO_UNDERSCORE=True"
      - "DISCORD_TOKEN=${UTIL}"
      - "HID=${HID}"
  haxicord:
    build: ./haxicord/
    restart: always
    pid: "host"
    entrypoint: bash /app/run.bash
    volumes:
      - "./haxicord/run.bash:/app/run.bash"
      - "./haxicord/Main.hx:/app/src/Main.hx"
      - "./haxicord/build.hxml:/app/build.hxml"
    environment:
      - "DISCORD_TOKEN=${HX}"
      - "HID=${HID}"