#!/bin/bash
SP="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
cd $SP
docker-compose up -d
if !(test -d "./logs"); then
    mkdir ./logs
fi
l=("discord.py" "discordgo" "discord.js" "eris" "discordrb" "discordia" "logging_dummy" "misc_dummy" "insecure_dummy" "discord.jl" "discordcr" "garbage_dummy" "rpc1" "rpc2" "rpc3" "rpc4" "detriusjs" "dimscord")
for i in ${l[@]}; do
    ii="bots_${i//./}_1"
    i="$i.log"
    f="./logs/$i"
    if test -f $f; then
        rm $f
        touch $f
    fi
    docker logs -f $ii &> $f &
done
if test -f "./logs/all.log"; then
    rm ./logs/all.log
    touch ./logs/all.log
fi
docker-compose logs -f --no-color &> ./logs/all.log &