version: "3"
services:
  bot:
    build: .
    restart: on-failure
    entrypoint: python3 -u /app/discord.py.py
    volumes:
      - "./:/app"
    environment:
      - "JISHAKU_HIDE=True"
      - "JISHAKU_NO_UNDERSCORE=True"
      - "DISCORD_TOKEN=NzU4NTQ0MzE0MzA5MDE3NjIz.X2wfcQ.hua_KKq59y0TTvFCyS5vi8pMm8U"