#!/bin/bash
SP="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
cd $SP
docker-compose -f $SP/docker-compose.yml up -d
rm ../logs/discord.py.log&&touch ../logs/discord.py.log
docker logs -f discordpy_bot_1 &> ../logs/discord.py.log &