#!/bin/bash
SP="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
echo stopping...
docker-compose down
echo starting...
docker-compose -f $SP/docker-compose.yml up -d
rm ../logs/discordrb.log&&touch ../logs/discordrb.log
docker logs -f discordrb_bot_1 &> ../logs/discordrb.log &